sudo: required
language: python
services:
  - docker
python:
  - '3.6'
install: pip --version
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web bash -c "python wait_for_database.py; coverage run --source='.' manage.py test; coveralls"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo $HEROKU_AUTH_TOKEN | docker login -u _ --password-stdin registry.heroku.com;
    docker tag foodie-server_web registry.heroku.com/foodie-g4/web;
    docker push registry.heroku.com/foodie-g4/web;
    fi
notifications:
  email: false
cache:
  pip: true
