sudo: required
language: python
services:
  - docker
python:
  - '3.6'
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web bash -c "python wait_for_postgres.py; python manage.py test"
deploy:
  script: echo $HEROKU_AUTH_TOKEN | docker login -u _ --password-stdin registry.heroku.com;
          docker tag web registry.heroku.com/foodie-g4/web;
          docker push registry.heroku.com/foodie-g4/web
notifications:
  email: false
cache:
  pip: true
