# Generated by Django 2.2.5 on 2019-12-02 01:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('unassigned', 'unassigned'), ('in_progress', 'in_progress'), ('delivered', 'delivered'), ('deliver_error', 'deliver_error')], default='unassigned', max_length=100)),
                ('date_time_ordered', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('delivery_price', models.FloatField(blank=True, null=True)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('start_address', models.TextField(blank=True, null=True)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('end_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
