# Generated by Django 2.2.5 on 2019-10-30 23:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191030_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
