# Generated by Django 2.2.5 on 2019-11-02 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191031_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UA', 'unasigned'), ('IP', 'in progess'), ('D', 'delivered'), ('DE', 'deliver error')], default='unasigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_user',
            field=models.ForeignKey(default=None, limit_choices_to={'is_delivery': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
