# Generated by Django 2.2.5 on 2019-11-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191102_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('in progress', 'in progress'), ('delivered', 'delivered'), ('deliver error', 'deliver error')], default='unassigned', max_length=100),
        ),
    ]
