# Generated by Django 2.2.5 on 2019-11-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191103_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('in_progress', 'in_progress'), ('delivered', 'delivered'), ('deliver_error', 'deliver_error')], default='unassigned', max_length=100),
        ),
    ]
