# Generated by Django 2.2.5 on 2019-12-02 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField()),
                ('order', models.ForeignKey(limit_choices_to=models.Q(('status', 'delivered'), ('status', 'deliver_error'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.Order')),
            ],
        ),
    ]
