# Generated by Django 2.2.5 on 2019-09-30 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_location_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
