# Generated by Django 2.2.5 on 2019-11-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191014_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FCMToken',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
