# Generated by Django 2.2.5 on 2019-11-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FCMToken',
            field=models.CharField(max_length=300),
        ),
    ]
