# Generated by Django 2.2.5 on 2019-11-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191105_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recuperation_token',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
