# Generated by Django 2.2.5 on 2019-11-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reputation',
        ),
    ]
